### ISSUE TITLE
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect

### ISSUE THREAD

**Issue by joseAlex27** [spatie/laravel-backup#1097]
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect

pls help with this issue

**Comment by rhalp10** [comment]
> Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect
> 
> pls help with this issue

try this if this work for you:
**config/database.php**
```
'mysql' => [
	'dump' => [
               'dump_binary_path' => 'C:\\wamp64\\bin\\mysql\\mysql8.0.18\\bin', // only the path, so without `mysqldump` or `pg_dump`
               'use_single_transaction',
               'timeout' => 60 * 5, // 5 minute timeout
               // 'exclude_tables' => ['table1', 'table2'],
               'add_extra_option' => ' --column-statistics=0', 
            ] , 
]

```
[Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect](https://github.com/Laravel-Backpack/BackupManager/issues/55#issuecomment-465981423)
