### ISSUE TITLE
How to restore from a backup

### ISSUE THREAD

**Issue by KHucks** [spatie/laravel-backup#112]
As I learned from #23 there is no artisan command to restore from a backup - ok I understand that.

But what is the way to actually do a restore from a backup? Making regular backups without a way to acutally use them in the emergency case seems a little 'interesting'.

What am I missing here? I could not find anything about it in the docs.

Fiddle around with it manually on something that is very likely the production environment?

Any hint is greatly appreciated as the package does make a very good impression!

**Comment by freekmurze** [comment]
The package does not have restore capabilities because virtually everybody does it a little differently and there are a lot of different ways to restore things. It all depends on what type of project and what went wrong.

On my projects, mostly I'll do manual restores. If you want to automate restores, you should write your own scripts to do so.

**Comment by vesper8** [comment]
I understand why you don't want to add a full restore functionality. However I think it would be useful if you added a few more artisan commands that would list the latest backups with their size and date. And would allow you to "pull" a backup back. I store my backups on S3 and if I wanted to do a restore I would do it fully from the server because pulling to my local machine and then uploading that's a nightmare because of file size and slow internet.

So right now I would of course write a script to pull the file manually via s3 or even do it on the command line somehow. But it would be useful if you at least provided that as part of your application. Just pulling it back and dump it in a folder, maybe even include extractions. And let us do the rest from there. Thoughts?

**Comment by freekmurze** [comment]
I'd accept a PR that displays a list of the latest backups on a specific disk.
