### ISSUE TITLE
Empty backupName

### ISSUE THREAD

**Issue by mohammadteimoori** [spatie/laravel-backup#113]
backupName attribute in backupDestination is always empty while backup was successful and zip file exists in path. Following is the content of handled object in BackupWasSuccessfulListener :

![screen shot 2016-04-12 at 16 06 22](https://cloud.githubusercontent.com/assets/13310763/14462944/7c2ac3d4-00c9-11e6-8957-18f99f56ca94.png)

I need to get filename and store it in database.

**Comment by freekmurze** [comment]
By default the package will use `env('APP_URL')` to determine the name. Could you check if you're using that in the backup config file and if so that that environment variable is indeed set.

The filename of the zip isn't included in the event. If you're using a local disk, you could just get the name of the oldest file in the destination directory where your backups reside.

**Comment by mohammadteimoori** [comment]
I always get env('APP_URL') value as backupName and no backup name. Maybe backupName is not applicable when using local disk.

![screen shot 2016-04-15 at 12 49 26](https://cloud.githubusercontent.com/assets/13310763/14559377/93fa49da-0308-11e6-988e-3c9d158810cd.png)

**Comment by freekmurze** [comment]
In your screenshot `backupName` is being filled.
