### ISSUE TITLE
Unreachable backup destination

### ISSUE THREAD

**Issue by unamix** [spatie/laravel-backup#133]
I have a custom webdav Filesystem Disk.  
When i do:
```
Storage::disk('webdav')->put('file.txt', 'Contents');
```
the file gets successfully written to my webdav storage disk.

When i run php artisan backup:list i get the following error:

> Unreachable backup destinations  
> Could not reach backups for App on disk webdav because:  
> HTTP error: 404

I'm using "league/flysystem-webdav": "^1.0".

My Service Provider:
```
public function boot()
 {  
    Storage::extend('webdav', function($app, $config) {`
        $client = new Client($config);
        $adapter = new WebDAVAdapter($client);
        return new Filesystem($adapter);
    });
}
```

My filesystem config:
```
'webdav' => [
    'driver' => 'webdav',
    'baseUri' => 'https://' . env('STACK_USERNAME') . '.stackstorage.com/remote.php/webdav/',
    'userName' => env('STACK_USERNAME'),
    'password' => env('STACK_PASSWORD'),
],
```

TransIP Stack gives you 1TB free cloud storage so i would be nice to get this working. Can you help me? If you need credentials for testing pm me.

**Comment by freekmurze** [comment]
I'm thinking that this issue is not caused by this package, but by something in your application. Laravel backup just uses the configured disk in a Laravel app. Nothing special is done with them.

You could try debugging by putting `var_dumps` and `dd` in this class: https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/BackupDestination.php  The `disk` property is the disk where the package will try to copy files to.

**Comment by unamix** [comment]
Thanks @freekmurze! Turns out I had to create the folder (set in env('APP_URL')) on my webdav disk manually. Works fine now :)
