### ISSUE TITLE
Feature request: command to restore, symmetric to backup command; also backup stack

### ISSUE THREAD

**Issue by rulatir** [spatie/laravel-backup#150]
I need quick and easy-to-use backup/restore functionality that I will use literally dozens of times a day during development. This is badly needed because of Laravel migrations' **DREADED AND CURSED** inability to recover from incomplete, borked migrations. Having to delete all tables manually and truncate the migrations table everytime you make a silly mistake in migration code severely taxes development productivity.

I'd imagine an interface like this:

```
$ php artisan backup:pushdb
$ php artisan migrate
ERROR: something went wrong, we are left with incomplete migration that cannot be rolled back
$ php artisan backup:popdb
```

**Comment by freekmurze** [comment]
There is an option to only backup the database: 

```php
php artisan backup:run --only-db
```

You can use that command in your deployment script right before running migrations.

Because everybody restore data differently this package doesn't provided an automated way to this. If you want to restore an entire db, I suggest you write the command for that in your application or a separate package.
