### ISSUE TITLE
Backups to S3 fail after updating to 8.1.1

### ISSUE THREAD

**Issue by mike-healy** [spatie/laravel-backup#1517]
After doing a composer update and brininging Spatie Laravel Backup up from `8.0.1` to `8.1.1` (and also Laravel `9.0.1` to `9.6.0`) my backup jobs started failing with a permissions error.

Downgrading the package to `8.0.1` solved the problem. Other parts of my app that use an S3 disk continued to work correctly after the upgrade.

The error returned was
```
Could not connect to disk cloud because: exception 'Aws\S3\Exception\S3Exception' with message
'Error executing "ListObjects" on <redacted>;
AWS HTTP error: Client error: GET <redacted> resulted in a 403 Forbidden response
```

**Comment by freekmurze** [comment]
Seems like my backups are working fine with this version. I'd appreciate a PR that fixes this.

**Comment by mike-healy** [comment]
I'll see if I can find the issue and submit a PR

**Comment by mike-healy** [comment]
I discovered that `8.0.5` introduced an `isReachable()` check which was failing for me because my AWS user didn't have `ListBucket` access. The job worked previously because the user did have write permissions.

I've added that permission to IAM to resolve.
I have submitted an unrelated PR for a minor improvement I discovered while tracking this down.

**Comment by dreammonkey** [comment]
Hi, I'm having a similar issue, but I'm currently unable to give the IAM user the ListBucket permission.
My setup is slightly different because I'm using a different user for each environment my app runs in (i.e. local, staging, production).

In IAM I have 3 users and they all have the following permission policy, effectively granting each user full access to their own (home) folder and nothing else...

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAllS3ActionsInUserFolder",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/${aws:username}/*"
            ]
        }
    ]
}
```

This setup has worked well for quite some time, but since the afore mentioned update it started throwing the error message like stated in the original post. When I disable/comment out the `isReachable` check, the backup runs fine...

I'm clearly allowing all S3 permissions to the user locations, so I'm really scratching my head as to why the ListObjects method is failing...

Any ideas are much appreciated !

PS: I know this question is more related to writing IAM policies than it is to the internal workings of this package but I'm  hopeful someone could shine a light on this issue.

**Comment by dreammonkey** [comment]
Answering my own question (sooner than expected 🤣 )

This policy did the trick:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my-bucket",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "",
                        "${aws:username}/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::my-bucket/${aws:username}",
                "arn:aws:s3:::my-bucket/${aws:username}/*"
            ]
        }
    ]
}
```
