### ISSUE TITLE
Multi-Tenant Application DB Backup

### ISSUE THREAD

**Issue by vik0803** [spatie/laravel-backup#167]
Hi,

I have reviewed that we do have an option to backup multiple databases but as we are building Multi tenant application that changes the database dynamically depending on users account. Do we have a capability to provide the databases information via a controller that can use the dbhost, dbname, uname and pwd dynamically and take care of backing up all the databases?

Appreciate your help.

Thanks,
Vik

**Comment by freekmurze** [comment]
There's currently no easy way to do this.

But take a look at [this code](https://github.com/spatie/laravel-backup/blob/master/src/Commands/BackupCommand.php#L29). You could feed the `createFromArray` function your own configuration and the call `run` on the object it returns.

**Comment by surgiie** [comment]
I know this issue is old, but i wanted to share my solution. Im building a multi tenant setup as well and we swap out database connections depending on which tenant domain is hitting the application. For my case i only want to create backups of the database. So i wrote a wrapper to the `backup:run` command:



```


   /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $domain = $this->argument('domain');

        $tenant = Tenant::where('domain', $domain)->first();
        if (!$tenant) {
            return $this->error("Tenant with domain {$domain} could not be found.");
        }

        //make sure we kill the current connection
        DB::purge('mysql');

        config(['database.connections.mysql.database' => $tenant->db]);

        $this->call('backup:run', [

            '--only-db'=>true,
            '--db-name'=>['mysql']
        ]);
    }

````

Probably not the best solution, but hopefully it helps anyone out! @vik0803
