### ISSUE TITLE
Failed to backup  because: No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by mskenderian** [spatie/laravel-backup#168]
I have a few web apps using the amazing laravel-backup. this morning i got an email stating: "Failed to backup  because: No supported encrypter found. The cipher and / or key length are invalid.", it backs up the DB twice a day. The issue i have with this error, it doesnt tell me which one of my apps it is. Also normally the backups are fine and i have not changed or updated the code. on any of my web apps in the  paste few days. So i am not sure why its failing.

**Comment by freekmurze** [comment]
That error suggest that one of your Laravel apps don't have a valid app key. You should figure out which app it is and probably run `php artisan key:generate` to generate a valid key. I'm guessing the problem was not caused by this package. Please reopen if, after your research, it was our package that made the error.
