### ISSUE TITLE
Problem with cronjob - Directory nonexistent

### ISSUE THREAD

**Issue by Machecek** [spatie/laravel-backup#179]
Hi,

first of all thanks for great package, i really like it. I have set it up to my server, tested running "backup:run" in console - everything runs well

The problem really is that when i set up Laravel CRON (Kernel.php), server is unable to create backup and i'm getting this error to my laravel.log:
```php
local.ERROR:  backups : error: Failed to backup  because: The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create [PATH_TO_STORAGE]/storage/laravel-backups/temp//mydb.sql: Directory nonexistent
```
 
Is there any overcome on this issue?

Cron is run as www-data (apache user)
In my Kernel i have: 
```php
$schedule->command('backup:run')->daily()->at('02:00');
```

**Comment by freekmurze** [comment]
The code in the kernel looks ok. It look like the error is not related to this package, but a permission problem on your server.

**Comment by lukepolo** [comment]
I also have this same issue 

event when running as sudo . I am using laravel homstead for testing , it also fails on dev server (forge).


sudo php artisan backup:run
Starting backup...
Dumping database program_management...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create /tmp/0.02741300 1485977081/db-dumps/program_management.sql: Directory nonexistent

**Comment by joseAlex27** [comment]
> The code in the kernel looks ok. It look like the error is not related to this package, but a permission problem on your server.

The same answer to everyone!!!!!!..............
