### ISSUE TITLE
Schedule cron job command not execute

### ISSUE THREAD

**Issue by patelchirag123** [spatie/laravel-backup#180]
Hi,

i set install and set below schedule command in kernal.php file. and i set below cron job on my server.

Command: **$schedule->command('backup:run');** 

Cron job:   **5 * * * * php /var/www/html/shravan/artisan schedule:run >> /dev/null 2>&1**  (runs every five minute)

My problem is after 5 minute not generate backup zip file in my storage folder. 
If i execute command manually  **php artisan cron:job**   then zip file is generate but when i scheduling using cron job at that time not generate zip file.

Is there any issue in my cron job command for this  issue?

**Comment by freekmurze** [comment]
Hi,

if the job runs fine when you call it manually, and it does not run scheduled that means that 
- you did not set up the scheduling correctly in Kernel.php (please refer to the laravel docs)
- or there's something wrong with your cron process.

Please reopen if it turns out there is an error with our package.
