### ISSUE TITLE
 ''mysqldump'' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rob1121** [spatie/laravel-backup#289]
''mysqldump'' is not recognized as an internal or external command, operable program or batch file.

sir, what might be the problem?

**Comment by freekmurze** [comment]
This package is not compatible with Windows servers.

**Comment by stevebauman** [comment]
😢

**Comment by Manasa-HK** [comment]
Hello,

you can go to the installation path in C:\ .,
I just used as below.,

C:\> cd C:\Program Files\MySQL\MySQL Server 5.7\bin 

this works...

**Comment by NazarAli** [comment]
i have same problem is there any help ??

**Comment by pinoywebs123** [comment]
Hey guys if you are using windows like mine windows 10.
I am currently using XAMPP
steps
1. right click my computer icon
2. select "Properties"
3. select "Advance system settings"
4. select "Environment Variables" lower right
5. Select "NEW" Take note this is for the upper one. Because you can see 2 New Button. So better Select the upper part.
6. Variable Name  Add "Path"
7. Variable Value will be location of mysql bin in my side since I used XAMPP " C:\xampp\mysql\bin"
8. Select OK, OK, OK until you finished
9. Disclaimer if you install mysql community or whatever you install. Just find the path for mysql/bin to any in your directory.
10. close all command console/git console then open again to test it type mysqldump if there are still error , Restart your computer.
11. Your welcome Happy coding

**Comment by NihirRootways** [comment]
Please add `C:\xampp\mysql\bin` to this path at your user variables and system variables; if you are using a wamp server, add `C:\wamp64\bin\mysql\mysql8.0.27\bin` to this path at your user variables and system variables.

**Note: MySQL version path will change as per your installation**
