### ISSUE TITLE
Run in controller

### ISSUE THREAD

**Issue by BangShut** [spatie/laravel-backup#318]
How to run in controller for backup all file and database ?

**Comment by freekmurze** [comment]
```php
\Artisan::call('backup:run');
```

**Comment by agentphoenix** [comment]
I'm working on an update system for my app that attempts to backup the site files and database before it runs any destructive updates. This package fits the bill perfectly, but since this app will most often be run on shared hosting (and by people with little programming/server management experience), I don't want to rely on the command line to do that. The natural place to turn is running the Artisan command in the controller.

As I dug into this though, I found that it didn't work very well. Yes, running the command will still do everything it should, but I've run into an issue along the way. Maybe there's a way to do what I want and I'm just not seeing it, so if that's the case, please point me in the right direction.

The issue that I ran into was that the `BackupJob@run` method tries to output everything to the console when there's an error. Since there's no return from that method or exception thrown, if the backup process errors out (either because of `mysqldump` not being available or whatever else), I have no idea and no way to notify the user that the backup failed and they need to manually do a backup before they attempt to continue the update process.

So I guess my question is: what's the best way to run the backup from a controller and still be able to catch exceptions or know what's happening and act on that from the controller? Any ideas? @freekmurze
