### ISSUE TITLE
Temporary directory doesn't exist, due to space char

### ISSUE THREAD

**Issue by graystevens** [spatie/laravel-backup#358]
It seems 4.4.2 introduced a bug with the temporary directory containing a space char:

`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create /tmp/0.83890900 1485990954/db-dumps/wisedb.sql: Directory nonexistent`

Rolling back to 4.4.1 fixes the issue.

**Comment by marcusmoore** [comment]
Looks like [spatie-temporary-directory](https://github.com/spatie/temporary-directory) was added in 4.4.2. What operating system and does it happen consistently?

**Comment by funcoding** [comment]
Even I am facing the same issue. I am using Ubuntu 14.04

**Comment by freekmurze** [comment]
This problem has been fixed in the underlying `spatie/temporary-directory` package. 

Just run `composer update` to pull in the fix.

My apologies for any inconvenience.

**Comment by dvlpp** [comment]
I'm following this thread because I'm experiencing the same issue, either on OSX and Ubuntu 14.04; I tried with the 4.4.4 version, after the https://github.com/spatie/laravel-backup/pull/360 PR, without success. For now, I downgraded to 4.4.1.

On OSX, error is:
`Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/folders/zn/xqkqcz2x6z195fjlpq7gm2c00000gn/T/0.221896001486038964/db-dumps/radar-prod.sql: No such file or directory`

**Comment by freekmurze** [comment]
We're working on a new fix.
