### ISSUE TITLE
Back up is ignoring excluded directories

### ISSUE THREAD

**Issue by bencarter78** [spatie/laravel-backup#378]
Hi

I'm currently using Laravel 5.4.11 with v3.5 of laravel-backup and I've noticed that when the backup runs it is ignoring the directories listed in the 'exclude' array, it's including all vendor and node_module sub-directories.

Any ideas why this might be? Is v3.5 compatible with L5.4? My server is running PHP 5.6 at the moment so upgrading to v4 isn't an option at the minute.

Thanks

**Comment by AlexVanderbist** [comment]
Hi Ben,

Is there are reason you are using `v3.5` instead of the latest release for v3 (`v3.10.2`)? If not, could you try updating to `3.10.2` and let me know if that solves the issues?

Thanks!

**Comment by bencarter78** [comment]
Hi @AlexVanderbist I have updated to 3.10.1 (3.10.2 requires L5.1|5.2|5.3) but it's still ignoring the exclude array

**Comment by bencarter78** [comment]
I think I've worked out the problem, it fails the shouldExclude method because in Laravel 5.4 the contains method has had it's signature altered ($key and $value have swapped).

Basically, it seems like v3.* is only compatible with Laravel 5.3 and below.

**Comment by AlexVanderbist** [comment]
Hi, I just stumbled uppon the same block of code. The key/value order change has already been introduced in Laravel 5.3 tho, that's why v3.10.2 of this package removed `contains` from the `shouldExclude` method altogether.

This means the package _might_ just work for L5.4. Feel free to fork the package, bump the required version in `composer.json` and test this out.
