### ISSUE TITLE
Backup each table in single file

### ISSUE THREAD

**Issue by dhcmega** [spatie/laravel-backup#413]
Hi, I don't know if this is actually and issue, if it's not, I'm sorry.
I couldn't find a way in which all tables can be dumped individually. I case the whole backup takes several gigabytes, having to download the whole thing from the S3 bucket and then decompress and then have to extract the create and insert from the huge file so one table can be restored is very impractical.
Would it be possible to alter this package to be able to handle it or will it need a major rewrite?
It should connect to the database, query the table list and the loop over the result generating the files.
Thanks!

**Comment by freekmurze** [comment]
The underlying package that takes of dumping the db is [spatie/db-dumper](https://github.com/spatie/db-dumper). Currently it cannot dump each table to a seperate file. Because I don't need this functionality myself I'm not going to invest any time in it myself. But I'd probably accept a PR is that functionality can be added in a non complex way.
