### ISSUE TITLE
.env file seems to be ignored

### ISSUE THREAD

**Issue by d-lamers** [spatie/laravel-backup#437]
I have included two folders and the separate file of .env but int he zip .env is missing

My config is like so:

`'files' => [

                /*
                 * The list of directories that should be part of the backup. You can
                 * specify individual files as well.
                 */
                'include' => [
                    storage_path('app/public'),
                    base_path('.env'),
                    storage_path('logs')
                ],

                /*
                 * These directories will be excluded from the backup.
                 * You can specify individual files as well.
                 */
                'exclude' => [],

                /*
                 * Determines if symlinks should be followed.
                 */
                'followLinks' => true,
            ],`

**Comment by freekmurze** [comment]
Is the `.env` file included if you backup the entire `base_path`?

**Comment by sebastiandedeyne** [comment]
Not sure, but I think you can only include directories, not single files.

**Comment by m1guelpf** [comment]
@d-lamers Why don't you do
``` php
base_path().'.env';
```

**Comment by d-lamers** [comment]
Ill have to test the whole directory when i'm back from a holiday break. @sebastiandedeyne the comment in the config says it does allow for individual files. @m1guelpf that does exactly the same. But thanks for thinking with me guys.

**Comment by sebastiandedeyne** [comment]
Only read the first line 🙈 

Enjoy your holiday break :)

**Comment by freekmurze** [comment]
You sure [can include single files](https://github.com/spatie/laravel-backup/blob/733694f/tests/Unit/FileSelectionTest.php#L135-L150) as well. 

I've also used your exact configuration in a test app and the `.env` seems to be backed up. 

Maybe the problem is that your application to unzip the backup doesn't see files starting with dot?
Here's [the result of my backup](https://www.dropbox.com/s/hg05xoziblau1mq/backup%20test.zip?dl=1). There's an `.env` file there (only contains default values for my local environment, nothing sensitive there). Can you see it?

**Comment by freekmurze** [comment]
Reopen if this is still an issue.

**Comment by sebastiaanluca** [comment]
I've had this issue as well, but only if `include` only contains `base_path('.env'),` and nothing else. Temporarily fixed this for my apps by including `storage_path('app'),` (which I don't really use and is empty).

**Comment by freekmurze** [comment]
I've tagged a new release that fixes this.

**Comment by sebastiaanluca** [comment]
Awesome and quick as always, thanks!
