### ISSUE TITLE
dropbox - no disk set for backup destination

### ISSUE THREAD

**Issue by w1n78** [spatie/laravel-backup#471]
hello, i am able to do use local without a problem, but when i use dropbox driver i run into errors.

in terminal i get
> Copying zip failed because: There is no disk set for the backup destination.

when i review the email, here's the error it gives me

> Important: An error occurred while backing up Short Term Training Database

Exception message: There is no disk set for the backup destination

Exception trace: #0 /Users/sherwin/apps/laravel/sttdb/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(78): Spatie\Backup\Exceptions\InvalidBackupDestination::diskNotSet() #1 

when i run backup:clean i get a
> invalid driver [dropbox] is not supported

i've checked your blog, i've destroyed the app api and recreated a new one. i googled issues relating to this and tried different things from those posts. not sure what else i'm missing. please help.

i have tried config:clear.

filesystem.php contains the following

```
'dropbox' => [
    'driver' => 'dropbox',
    'authorizationToken' => env('DROPBOX_TOKEN'),
],
```

also copied the DropboxFilesystemProvider.php file from https://murze.be/2017/04/dropbox-will-turn-off-v1-of-their-api-soon-its-time-to-update-your-php-application/

i'm using laravel 5.4.27, mysql 5.7.16

thanks.

**Comment by dib258** [comment]
Same here :(

I get : `Copying zip failed because: There is no disk set for the backup destination.`

I followed the instructions in the [Laravel Documentation](https://laravel.com/docs/5.4/filesystem#custom-filesystems) and the blog post ww1n78 showed.

Is there something more to know ?

Thanks in advance for your answer !

**Comment by dib258** [comment]
@w1n78 Found out what was the problem for me. I'm sure it's the same for you.

Just add `App\Providers\DropBoxServiceProvider::class,`

at the end of the providers in the `config/app.php`

:)

**Comment by freekmurze** [comment]
@w1n78 could you check if @dib258 's solution works for you? If it does, close this issue.

**Comment by w1n78** [comment]
@freekmurze @dib258 

okay i got! so it was a combo of different things. mainly related to file/class names. i was looking at different posts that used different names. one had DropboxServiceProvider the other used DropboxFilesystemServiceProvider. next the config key value on one article used authorizationToken while the other used accessToken.

after lining those up, it worked. thank you both for the help.

**Comment by subdesign** [comment]
@dib258 Same here.. but if I add the service provider, on my live server I get a strange not-so-related error: `Class cache does not exist`

On local dev, if I add the provider line to `app.php`, the db backed up nicely, and added to dropbox.  It not directly related to cache, because caching works well with redis (the driver set)

my issue on that: https://github.com/spatie/flysystem-dropbox/issues/32
