### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by dvidke** [spatie/laravel-backup#537]
Hello!

Do you guys have any clue about this error?

In my web.php:

```
Route::get('test-class',function(){
    dd(new ZipArchive());
});
```
Everything is working as expected:

![ashampoo_snap_2017 10 02_21h54m04s_001_](https://user-images.githubusercontent.com/6059573/31096404-3a1b1f5c-a7bc-11e7-99df-6355c951e997.png)

This is maybe prove that the zip ext is enabled and working (beside that the phpinfo() showing the same).

But when I call backup:run the following is appearing in the error log (1st line):

> [2017-10-02 17:52:03] production.ERROR: Class 'ZipArchive' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'ZipArchive' not found at /var/www/oravilag2/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php:49)

Could you help me to find the problem?

Please, let me know if you need some more specific info.

**Comment by freekmurze** [comment]
The PHP configuration used to handle webrequests is not the same as the PHP configuration used to handled CLI requests. Probably you don't have the zip archive installed on the PHP configuration used on the CLI.

The problem is probably not caused by this package, but is something specific to your server.
