### ISSUE TITLE
Error in php artisan backup:run

### ISSUE THREAD

**Issue by andraeinstein** [spatie/laravel-backup#542]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in /home/a
  ndraeinstein/Dropbox/ProjectBAT/ERP/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestinationFactory.php on line 13

how can fix this? 
Thanks

**Comment by hightekjonathan** [comment]
What does line 13 of that file look like?

The error suggest your'e trying to pass a variable, but it of null type instead of the required string

**Comment by introwit** [comment]
@andraeinstein Hi :) Be default this package uses your `APP_NAME` for the backup folder, what is the app name set for your app?

**Comment by andraeinstein** [comment]
@hightekjonathan  
this is line 13

return BackupDestination::create($filesystemName, $config['name']);

@introwit 
where i can find that app name? thanks sir

**Comment by introwit** [comment]
@andraeinstein in your config/app.php file, what's the name set to?

**Comment by andraeinstein** [comment]
@introwit  this is my app.php
   `'name' => 'Laravel',
    'env' => env('APP_ENV', 'production'),
    'debug' => env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
    'timezone' => 'Asia/Jakarta',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'key' => env('APP_KEY'),

    'cipher' => 'AES-256-CBC',
    'log' => env('APP_LOG', 'single'),

    'log_level' => env('APP_LOG_LEVEL', 'debug'),`

**Comment by introwit** [comment]
@andraeinstein Change the line having the `name` property to [this](https://github.com/laravel/laravel/blob/master/config/app.php#L16) and in your `.env` file set the name of your app like [this](https://github.com/laravel/laravel/blob/master/.env.example#L1). Try to run the command again after that & let me know how it goes :)

**Comment by jelgervisser** [comment]
@andraeinstein By default older versions of Laravel (i.e. <= 5.3) came without the variable APP_NAME in the environment file. So, if you have upgraded your application from <= 5.3 to >= 5.4 this entry might be missing. And that's a problem because the config file of the backup package expects this entry, see line 11 in config\backup.php.

**Comment by freekmurze** [comment]
Seems like this one has been answered. Reopen if this is still an issue.

**Comment by andraeinstein** [comment]
@introwit after change setting the app name, then i run php artisan config:clear
everything works perfectly. Thank u my friend

@jelgervisser im using laravel 5.5. 
@freekmurze thank you sir

Thanks all my friend for answering my questions :D

**Comment by shez1983** [comment]
the command ```php artisan backup:run --only-db``` was running perfectly for me but few days back it stopped running - i only realised today accidentally.. 

I get the 
```
 Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in .../vendor/spatie/laravel-backup/src/BackupDestination/BackupDestinationFactory.p  
  hp on line 14 
```
I have cleared the cache, set an explicit name in backup config name and its still nulll.. 

Not sure how if its been working fine, it has stopped working..

**Comment by lychuan** [comment]
php artisan backup:run
Starting backup...
Dumping database mayi...
Determining files to backup...
Zipping 562 files...
Created zip containing 562 files. Size is 12.61 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Copying zip failed because: Expected response code 250 but got code "500", with message "500 Error: bad syntax
".
Backup failed because Expected response code 250 but got an empty response.
#0 /Users/lianzhang/wwwroot/mayi/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)

**Comment by lychuan** [comment]
how can fix this?
Thanks
