### ISSUE TITLE
Error BackupDestination::create()

### ISSUE THREAD

**Issue by divdax** [spatie/laravel-backup#568]
Laravel 5.5 + laravel-backup 5.1.1

```
$ php artisan backup:run
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be
  of the type string, null given, called in /home/vagrant/www/project/vendor/spatie/laravel-backu
  p/src/BackupDestination/BackupDestinationFactory.php on line 13
```

**Comment by PhiloNL** [comment]
Same issue here after updating

**Comment by PhiloNL** [comment]
Found the issue. Add the following to your .env file:
`APP_NAME=foobar`

@freekmurze is there a reason why `env()` is used instead of `config()`?
It is recommended to use `config()` instead of `env()` when using `artisan config:cache`.
When using `config()` you will also get a default value in case something is not defined in the .env file.

> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files.

**Comment by divdax** [comment]
Thank you @PhiloNL - added missing env var and now it works. 😄

**Comment by arharp** [comment]
I also had this issue. I second @PhiloNL's question as to why env() is used instead of config().

**Comment by freekmurze** [comment]
I'd accept a non-breaking PR that changes the code to use `config()` instead of `env()`.
