### ISSUE TITLE
Large number of S3 HEAD requests

### ISSUE THREAD

**Issue by mikeaag** [spatie/laravel-backup#647]
Hi,

Sorry if this isn't the right place to post this.

I noticed that the S3 bucket i'm using to store backups is doing ~35k requests a month, which seemed like a lot. Looking into it, there seems to be about 1.1k HEAD requests happening each day.

I'm using Laravel Backup 4.19.2 and Laravel 5.4.36

I'm running `backup:clean`, `backup:run` and `backup:monitor`, once a day.

There are 37 backups currently in the bucket, and the bulk of the HEAD requests seem to happen when running `backup:clean`, with the rest happening running `backup:monitor`.

I am not using S3 for anything else with the site.

Is this expected behaviour?

Happy to provide more information if needed

Thanks

**Comment by AlexVanderbist** [comment]
Hi @mikeaag,

Last year I came across a similar issue where `backup:list` would use a ridiculous amount of API requests as well (https://github.com/spatie/laravel-backup/pull/422). This was due to the package recursively requesting meta data/directory listings and not caching those. On the local filesystem these requests are cached on OS level but obviously not for external filesystems resulting in a high number of API calls.

I think the easiest solution right now is to wrap Flysystem's S3 adapter in a caching adapter. Have a look here: https://flysystem.thephpleague.com/caching/.

Ideally we'd have to go through the package code and strategically cache/optimize the filesystem calls for those commands. But that might result in overcomplicating things by caching everything. Gonna leave this issue open and look into this soon

**Comment by jbardnz** [comment]
Did this issue get looked at further?

I just ran into the same issue, backing up my tiny site puts me over the AWS free tier usage as this package creates more than 20k requests each month.

**Comment by mikeaag** [comment]
@jbardnz I didn't end up looking into it any further. While i was going over the 20k request on the free tier, AWS were just writing off the £0.02 invoice each month, so i ended up ignoring it and focusing my time on other things.

Though i haven't tried it, @AlexVanderbist's suggestion of adding caching would most likely do the trick (though this isn't really a fix, more just covering up the problem).

If you happen to find a solution for this i'd be interested to hear what worked for you.

Cheers,
Mike

**Comment by dan-mesa** [comment]
I set this package up just a few days ago to complement DigitalOcean's weekly backup and was surprised to see a notification from AWS that I've already blown past the free 20K GET limit, and am on target for over 100K. Whether the implementation in this package accrues significant cost or not, it seems like a bug (or at least makes me uneasy) without caching baked in. Maybe this is fine though, and I'm just scared of runaway AWS.
