### ISSUE TITLE
Multiple Backup Sets

### ISSUE THREAD

**Issue by ksorbo** [spatie/laravel-backup#730]
It would be nice to have backup sets.

One use case would be to have a set that only backs up the database.
 
Looking at the config file, it would seem like it wouldn't be too hard to just create a different top level entry and put all the settings in that sub array, Then you could just run the command backup:run <setname>

(Don't yet have enough skill to do a pull request and do it myself!)

**Comment by freekmurze** [comment]
I'll keep this in mind when creating a new major version of the package. Might take a while though...

**Comment by ryancwalsh** [comment]
@freekmurze 

If I understand correctly, I was about to submit the same suggestion since what I was hoping to do doesn't yet seem possible:

I have a Laravel app, and I want to back up its DB every day, such as:

```
$schedule->command('backup:clean')->dailyAt(...
$schedule->command('backup:run --only-db')->dailyAt(...
```

But then I also have a console command that exports all of my Bitbucket issues into a json file on my server, and I want to back that file up using a different schedule and cleanup strategy. 

E.g. back it up weekly and only keep 8 backups.

So it seems like I'd need `spatie/laravel-backup` to support multiple config files or a nested config like suggested above.

Or is there some workaround?

Thanks so much for offering this cool tool. :-)

**Comment by freekmurze** [comment]
I'd like to keep this package very simple, if you need to backup stuff using different scenarios, it's probably best to use another, more versatile backup solution.

**Comment by vesper8** [comment]
@ryancwalsh did you figure out a good solution to your problem? I too would like to have backup sets, I already backup the databases from the files on a separate schedule but now in one project that uses multiple databases I find myself needing to backup some databases more frequently than others

**Comment by ryancwalsh** [comment]
@vesper8 No, I haven't. But if you end up finding a good solution, I'd appreciate you posting it here because I'm still interested. Thanks.
