### ISSUE TITLE
Old backup still monitored

### ISSUE THREAD

**Issue by amirpiri** [spatie/laravel-backup#788]
I have got old folder monitor notifications in slack, even though I removed it manually. It says there is no backup exist for the app!!!
But why this is happened?
I try to clear the cache with `php artisan cache:clear` but no success.

**Comment by freekmurze** [comment]
It isn't 100% clear what the issue is here. We recently tagged some bugfix releases that solve problems around the monitoring of backups. Could you try upgrading to the latest version? 

If the problem isn't fixed there, open up a new issue with a very clear explanation of what goes wrong and what you are expecting.

If you already have a fix in mind, feel free to open a PR.
