### ISSUE TITLE
OneDrive backup

### ISSUE THREAD

**Issue by fabianobn** [spatie/laravel-backup#853]
Hi, would you have any alternative to using laravel-backup with shipping to the onedrive?

**Comment by freekmurze** [comment]
Our package simply uses Laravel abstract filesystems. Which in turn uses FlySystem under the hood. In order to backup to OneDrive you should look for a OneDrive flysystem driver.

Here's how to register a flysystem driver in a Laravel app: https://laravel.com/docs/master/filesystem#custom-filesystems

And here's a driver: https://github.com/nicolasbeauvais/flysystem-onedrive

Good luck!

**Comment by fabianobn** [comment]
Ok @freekmurze Thankx!
