### ISSUE TITLE
empty folders will not be backed-up?

### ISSUE THREAD

**Issue by Voinay** [spatie/laravel-backup#859]
I have some empty folder in my project, it seems they are disappeared in the backup zip file. Is it possible to also backup empty folders?

**Comment by atymic** [comment]
What is your use case? Generally I would think that excluding empty folders makes sense.

**Comment by atymic** [comment]
ping @Voinay

**Comment by atymic** [comment]
cc @Voinay

**Comment by aske-cph** [comment]
I also have this problem! 

And @atymic isn't retaining a complete folder structure very important when backing up especially applications?

I mean the PHP code refers to for example a users files which are referred to via paths that simply need to be be there. And also the folders makes the foldersystem way easier to understand and look at.
For example all of our users have different folders pertaining to a lot of different things.

Now the app breaks because the PHP tries to list files in non existing folders which very much should be there, and you have no idea which folders "should be present" as subfolders in each folders as some are "randomly" removed because they are empty.
 
For example our users can create a "survey", creating this instantly creates both a DB entry _and all the files and folders needed for that survey_ in their users folder. For example a survey with 5 pages have folders [1,2,3,4,5] one for each page. Isn't that a pretty standard way to make a foldersystem? 
You can also have lots of other folders in the users app that are important. 

Removing empty stuff not only breaks the app but also makes "looking" at the folders manually way harder as they look different for each user and you don't have an idea of "what folders should be in this parent folder" by just for example looking at the first one.

Otherwise you need to make all code in your app that lists anything also be a check for existence/creation of that folder path - but that still doesn't solve the problem of missing "schematics" when downloading the backup.

**Comment by freekmurze** [comment]
I agree that ideally empty directories should be backupped as well.

I accept a PR that proves what the current behaviour for this package currently is.

I would suspect that empty directories do get backed up. If that isn't the case, I'd accept a PR that adds that behaviour.
