### ISSUE TITLE
Symphony deprecation error

### ISSUE THREAD

**Issue by JoshMountain** [spatie/laravel-backup#876]
`User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.`

This started popping up after upgrading to Laravel 5.8 - I can provide more detail if needed, feel free to ping me on the Laravel discord.

**Comment by freekmurze** [comment]
Could you provide a stracktrace?

**Comment by CBreetzi** [comment]
I have the same error. Here's the stacktrace.

`ErrorException: User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.
#23 /vendor/symfony/process/Process.php(147): Symfony\Component\Process\Process::__construct
#22 /vendor/spatie/db-dumper/src/Databases/MySql.php(137): Spatie\DbDumper\Databases\MySql::dumpToFile
#21 /vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(247): Spatie\Backup\Tasks\Backup\BackupJob::Spatie\Backup\Tasks\Backup\{closure}
#20 [internal](0): array_map
#19 /vendor/laravel/framework/src/Illuminate/Support/Collection.php(1034): Illuminate\Support\Collection::map
#18 /vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(250): Spatie\Backup\Tasks\Backup\BackupJob::dumpDatabases
#17 /vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob::createBackupManifest
#16 /vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob::run
#15 /vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Commands\BackupCommand::handle
#14 [internal](0): call_user_func_array
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::callBoundMethod
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::call
#10 /vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\Container::call
#9 /vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Console\Command::execute
#8 /vendor/symfony/console/Command/Command.php(255): Symfony\Component\Console\Command\Command::run
#7 /vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Illuminate\Console\Command::run
#6 /vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Spatie\Backup\Commands\BaseCommand::run
#5 /vendor/symfony/console/Application.php(901): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null`

**Comment by freekmurze** [comment]
Which version of the package are you using?

**Comment by CBreetzi** [comment]
Thank you for your fast answer!
Taken from composer.json
`"spatie/laravel-backup": "^6.0"`

**Comment by freekmurze** [comment]
Looking at the stracktrace the error happens in our `db-dumper` package. It's already resolved there. Make sure you're using a recent version of the package. v2.14 is currently the latests version.
