### ISSUE TITLE
mysqldump: Got error: 1049: "Unknown database 'laravel-6;'" when selecting the database

### ISSUE THREAD

**Issue by WorldSeso7** [spatie/laravel-backup#977]
With laravel 6 and a fresh install of the package I configured out to use the database connection "mysql" where the db name is "laravel-6".
I got an error dumping the db: a semicolon was inserted at the end of the db name and the command fails because it can't find the db.

**Comment by freekmurze** [comment]
Try clearing the config

```php
php artisan config:clear
```

**Comment by ryancwalsh** [comment]
I'm using "spatie/laravel-backup": "6.8.0" and "laravel/framework": "^7.0" and am having this problem right now too.

I get this error:

`mysqldump: Got error: 1049: Unknown database 'myDatabaseName;' when selecting the database`

Notice the unwanted semicolon in the name.

`php artisan config:clear` doesn't help.

I think the problem is the semicolon being added here: https://github.com/spatie/db-dumper/blob/2.15.3/src/DbDumper.php#L265

By the way, I'm using Windows (WAMP). This is my first attempt to use spatie/laravel-backup on WAMP (I've only ever used it on Ubuntu).

I've already added the `dump` array to my database config: https://spatie.be/docs/laravel-backup/v6/installation-and-setup#dumping-the-database

**Comment by freekmurze** [comment]
@ryancwalsh As I'm not on Windows, I'd accept a PR that fixes this for you.

**Comment by ryancwalsh** [comment]
Thanks for your response, @freekmurze !

I just removed the `dump` array from my database config. Then running `wsl cd /mnt/c/code/myproject && php artisan schedule:run 1>> NUL 2>&1` from Windows > Start > Run seems to work (using WSL Ubuntu).

So I then created a task that gets executed every minute by Windows Task Scheduler and runs `wsl cd /mnt/c/code/myproject && php artisan schedule:run 1>> NUL 2>&1` , and it seems like it is working.

So it's looking like I can use the Spatie packages the way they are. Thanks.
